# -- Flask server settings -- #

webapp:
  host: 127.0.0.1
  port: 5000
  debug: true

# -- FastAPI server settings (needed for API client) -- #

api:
  base_url: https://bcn-rainfall-api.onrender.com/rest