services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"