services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"