[project]
name = "bcn-rainfall-webapp"
version = "1.0.4"
description = "Webapp run with Flask to display in a user-friendly way rainfall data from the city of Barcelona, Catalunya."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcn-rainfall-api-client~=1.0.8",
    "flask~=3.1.0",
    "plotly~=5.24.1",
    "pre-commit~=4.0.1",
    "pydantic~=2.8.2",
    "pyyaml~=6.0.2",
]
authors = [{name = "Paul Charles", email = "paul.charles@tutanota.com"}]

